# coding=UTF8
## This file is part of VideoTester
## See http://video-tester.googlecode.com for more information
## Copyright 2011 Iñaki Úcar <i.ucar86@gmail.com>
## This program is published under a GPLv3 license

# Description: run test series with multiple .conf files (generated by test-generate-conf.py)

from subprocess import call

VT = './VT'
conf_path = 'test/'
tests = 8

for i in range(0, tests):
    test = conf_path + 'test-' + str(i) + '.conf'
    print 'Running ' + test
    call([VT, 'client', '-c', test])
print "\nFinished"